MADNESS: array_worldobject.cc File Reference
array_worldobject.cc File Reference
#include <madness/world/world.h>
#include <madness/world/worldgop.h>
#include <madness/world/world_object.h>
Classes
class Array
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References a, b, madness::WorldGopInterface::fence(), madness::finalize(), madness::Future< T >::get(), madness::World::gop, initialize(), MADNESS_ASSERT, N, print(), madness::World::rand(), madness::World::rank(), and madness::World::size().