MADNESS: testlda.cc File Reference
testlda.cc File Reference
#include <madness/world/MADworld.h>
#include <madness/mra/mra.h>
#include <madness/tensor/tensor.h>
#include <fstream>
#include "xcfunctional.h"
Classes
struct xcfunc_data_point
Functions
int main (int argc, char **argv)
void test_lda (World &world)
Function Documentation
main()
int main (int argc, char ** argv)
References SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::World::gop, madness::initialize(), and test_lda().
test_lda()
void test_lda (World & world)
References e(), madness::XCfunctional::exc(), madness::XCfunctional::initialize(), N, madness::print(), v, and madness::XCfunctional::vxc().
Referenced by main().