MADNESS: test_future2.cc File Reference
test_future2.cc File Reference
#include <madness/world/MADworld.h>
#include <madness/world/world_object.h>
#include <iomanip>
Classes
class Array
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References a, b, SafeMPI::COMM_WORLD, madness::WorldGopInterface::fence(), madness::finalize(), madness::Future< T >::get(), madness::World::gop, initialize(), length, MADNESS_CHECK, print(), madness::World::rand(), madness::World::rank(), and madness::World::size().