MADNESS: test_mtxmq.cc File Reference
test_mtxmq.cc File Reference
#include <madness/madness_config.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <madness/world/safempi.h>
#include <madness/world/posixmem.h>
#include <madness/tensor/cblas.h>
#include <madness/tensor/tensor.h>
#include <madness/tensor/mxm.h>
Macros
#define TIME_DGEMM
Functions
void crap (double rate, double fastest, double start)
int main (int argc, char *argv[])
void mTxm (long dimi, long dimj, long dimk, double *c, const double *a, const double *b)
void mTxm_dgemm (long ni, long nj, long nk, double *c, const double *a, const double *b)
double ran ()
void ran_fill (int n, double *a)
void timer (const char *s, long ni, long nj, long nk, double *a, double *b, double *c)
void trantimer (const char *s, long ni, long nj, long nk, double *a, double *b, double *c)
Variables
bool smalltest = false
Macro Definition Documentation
TIME_DGEMM
#define TIME_DGEMM
Function Documentation
crap()
void crap (double rate, double fastest, double start)
Referenced by timer(), and trantimer().
main()
int main (int argc, char * argv[])
References a, std::abs(), b, c, d(), e(), SafeMPI::Finalize(), SafeMPI::Init_thread(), m, MPI_THREAD_SINGLE, madness::mTxm(), madness::mTxmq(), posix_memalign(), ran_fill(), smalltest, timer(), and trantimer().
mTxm()
void mTxm (long dimi, long dimj, long dimk, double * c, const double * a, const double * b)
References a, b, c, and k.
mTxm_dgemm()
void mTxm_dgemm (long ni, long nj, long nk, double * c, const double * a, const double * b)
References a, b, c, madness::cblas::gemm(), madness::cblas::NoTrans, and madness::cblas::Trans.
Referenced by timer(), and trantimer().
ran()
double ran ()
Referenced by ran_fill().
ran_fill()
void ran_fill (int n, double * a)
References a, and ran().
Referenced by main().
timer()
void timer (const char * s, long ni, long nj, long nk, double * a, double * b, double * c)
References a, b, c, crap(), mTxm_dgemm(), madness::mTxmq(), and SafeMPI::Wtime().
Referenced by main().
trantimer()
void trantimer (const char * s, long ni, long nj, long nk, double * a, double * b, double * c)
References a, b, c, crap(), mTxm_dgemm(), madness::mTxmq(), and SafeMPI::Wtime().
Referenced by main().
Variable Documentation
smalltest
bool smalltest = false
Referenced by main().